blank_issues_enabled: false
contact_links:
  - name: Report a security problem privately
    url: https://github.com/STEMMechanics/.github/security/policy
    about: Please do not publish possible security problems in an issue.
